### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by etnt** [crownedgrouse/jason#1]
Hi,
I'm just wondering under what license this code is released?

**Comment by crownedgrouse** [comment]
hum ISC License like all my other project, but indeed, it is in my working directory, but forgot to add to git... thanks ! I will add it asap.

**Comment by crownedgrouse** [comment]
hi, license is now added. ISC was declared anyway in erlang files headers.
package is now available on hex under name jason_erl ...
thanks for the catch. I hope jason will fit to your needs, any feedback welcome ! 
closing, thanks !
