### ISSUE TITLE
Numeric values are encoded incorrectly

### ISSUE THREAD

**Issue by sergseven** [crownedgrouse/jason#8]
Expected the test(from examples) to pass:
```
?assertEqual("123.456789", jason:encode(123.456789)).
```

but the actual value is 

```
"123.456789000000001"
```

**Comment by crownedgrouse** [comment]
please precise Erlang/OTP release used.

**Comment by crownedgrouse** [comment]
Cannot reproduce. Please give precision on otp version, os and arch , or I will close.

**Comment by crownedgrouse** [comment]
1> jason:encode(123.456789).
"123.456789"

Closing as not reproduced and lack of information.
